# Numpy Lern

I am starting numpy on 22-03-2025, and i will complete it and upload it on git hub to day. (I am lerning from chai with code)


In [5]:
import numpy as np

### **Create array from list**

 

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print("1D array :",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]]) #array will take only a single array in it, that's why we use a third bracket to cover the other rows
print("2D array :",arr_2d)

1D array : [1 2 3 4 5]
2D array : [[1 2 3]
 [4 5 6]]


### **List vs numpy array**


In [ ]:
py_list = [1,2,3]
print("python list multiplication: ", py_list*2)

np_array = np.array([1,2,3]) # element wise multiplication
print("python array multiplication: ",np_array*2)

python list multiplication:  [1, 2, 3, 1, 2, 3]
python array multiplication:  [2 4 6]


Check the time between the list and np


In [ ]:
import time
#list
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation tinme: ",time.time()-start)
#np array 
start = time.time()
np_array = np.arange(100000) * 2 # attributes : start, stop, step and 2 is the scaler here 
print("\n Numpy Operation tinme: ",time.time()-start)


 List Operation tinme:  0.24034690856933594

 Numpy Operation tinme:  0.0005767345428466797


### **Creating array from scratch**

In [ ]:
zero = np.zeros((3,4)) # zero array
print("zeros array : \n",zero)

one = np.ones((3,4)) # ones array
print("One array: \n",one)

full = np.full((2,2),7)  # const number array
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0, 11, 2)
print("sequence array: \n",sequence)


zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.7388791  0.17307296 0.96161   ]
 [0.97937367 0.17282166 0.8371126 ]]
sequence array: 
 [ 0  2  4  6  8 10]


### **Vector, Matrix and Tensor**

In [24]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([[[2,3],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n",tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[2 3]
  [3 4]]

 [[5 6]
  [7 8]]]


### **Array Properties**

In [25]:
arr = np.array([[1,2,3],[4,5,6]])

print("shape : ", arr.shape)
print("Dimension : ",arr.ndim)
print("size : ",arr.size)
print("DType : ",arr.dtype)

shape :  (2, 3)
Dimension :  2
size :  6
DType :  int64


### **Array Reshaping**